AWSTemplateFormatVersion: 2010-09-09
Description: Keycloak on ECS Template for CloudFormation Demo.
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  EnvironmentType:
    Description: The environment type
    Type: String
    AllowedValues: ["Dev", "Staging", "Production"]
    Default: Production
  KeycloakAdminUsername:
    Description: Keycloak admin username
    Type: String
    Default: admin
  KeycloakAdminPassword:
    Description: Keycloak admin password
    Type: String
    Default: admin
  KeycloakDBName:
    Description: Keycloak database name
    Type: String
    Default: keycloak
  KeycloakHttpEnabled:
    Description: Enable HTTP for Keycloak
    Type: String
    AllowedValues: ["true", "false"]
    # TODO: scheme should be changed to `false` when production environment is used
    Default: "true"
 
Mappings: 
  KeycloakTaskDefinitionMap:
    Production:
      "Memory" : 2048
      "Cpu" : 1024
      "ContainerName" : "ecsdemo-keycloak"
      "ContainerImage" : "keycloak-sample:latest"
      "ContainerPort" : 8080
      "ContainerTLSPort" : 8443
      # https://www.keycloak.org/observability/health#_healthcheck
      "HealthCheckContainerPort" : 9000
      "HealthCheck" : "bash -c '{ printf \"HEAD /health/ready HTTP/1.0\\r\\n\\r\\n\" >&0; grep \"HTTP/1.0 200\"; } 0<>/dev/tcp/127.0.0.1/9000'"
  KeycloakServiceMap:
    Production:
      "DesiredCount": 2
      "HealthCheckGracePeriodSeconds": 60
      "RollingUpdateMinimumHealthyPercent": 0


Conditions:
  isKeycloakHttpEnabled: !Equals [!Ref KeycloakHttpEnabled, "true"]

Resources: 
# ALB for Keycloak
  # Public ALB
  PublicALBForKeycloak:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:      
      # Name must be lowercase letters because the ALB DNS Name must be lowercase letters as well.
      # If the DNS name contains uppercase letters, Keycloak's `redirect_uri` check fails, resulting in an `invalid_redirect_uri` error.
      Name: demo-keycloak
      Subnets: 
        - Fn::ImportValue: !Sub ${StackPrefix}-PublicSubnetOneId
        - Fn::ImportValue: !Sub ${StackPrefix}-PublicSubnetTwoId
      SecurityGroups: 
        - Fn::ImportValue: !Sub ${StackPrefix}-PublicALBSecurityGroup-ID
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-PublicALBForKeycloak
  # Public ALB Target Group
  PublicALBForKeycloakDefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${StackPrefix}-PubKeycloakDfTg
      TargetType: ip
      VpcId: 
        Fn::ImportValue: !Sub ${StackPrefix}-VPC-ID
      Port: 80
      Protocol: HTTP
      # Health check for Keycloak
      # https://www.keycloak.org/observability/health#_keycloak_health_check_endpoints
      HealthCheckPath: /health/ready
      HealthCheckPort: 9000
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 10
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-PubALBForKeycloakDfTg
  # Public ALB Listener
  PublicALBForKeycloakListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      LoadBalancerArn: !Ref PublicALBForKeycloak
      Port: 80
      Protocol: HTTP
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref PublicALBForKeycloakDefaultTargetGroup

# TODO: Not supported yet: HTTPS(443) 
#       Add HTTPS(443) Listener and Target Group(8443) for the public ALB for Keycloak

# ECS Cluster for Keycloak
  KeycloakECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${StackPrefix}-Keycloak-Cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-Keycloak-Cluster

# Log Group
  KeycloakECSLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/ecs/logs/${StackPrefix}-keycloak-ecs-group"
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-KeycloakECSLogGroup

# ECS Task Definition
  KeycloakECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${StackPrefix}-Keycloak-Task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Memory: !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, Memory]
      Cpu: !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, Cpu]
      ExecutionRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-ECSTaskExecutionRole-Arn
      TaskRoleArn:
        Fn::ImportValue: !Sub ${StackPrefix}-KeycloakECSTaskRole-Arn
      ContainerDefinitions:
        - Name: !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          Image: 
            Fn::Join:
              - ""
              - - !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/
                - !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, ContainerImage]
          Command:
            - 'start'
            - '--optimized'
          PortMappings:
            - ContainerPort: !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]
            - ContainerPort: !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, ContainerTLSPort]
            - ContainerPort: !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, HealthCheckContainerPort]
          HealthCheck:
            Command:
              - CMD-SHELL
              - !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, HealthCheck]
            Interval: 90
            StartPeriod: 60
          Environment:
            # Keycloak Configuration
            # https://www.keycloak.org/server/all-config#category-config?q=hostname
            # Keycloak Admin Account
            - Name: KC_BOOTSTRAP_ADMIN_USERNAME
              Value: !Ref KeycloakAdminUsername
            - Name: KC_BOOTSTRAP_ADMIN_PASSWORD
              Value: !Ref KeycloakAdminPassword
            # HTTP Enabled
            - !If
              - isKeycloakHttpEnabled
              - Name: KC_HTTP_ENABLED
                Value: 'true'
              - !Ref AWS::NoValue
            # Management(Health check) scheme
            - !If
              - isKeycloakHttpEnabled
              - Name: KC_HTTP_MANAGEMENT_SCHEME
                Value: 'http'
              - !Ref AWS::NoValue
            # Keycloak Hostname
            - Name: KC_HOSTNAME
              Value: !GetAtt PublicALBForKeycloak.DNSName
            # Cache Provider(Infinispan)
            - Name: KC_CACHE
              Value: 'ispn'
            - Name: KC_DB_URL
              Value:
                Fn::Join: 
                  - ""
                  - - "jdbc:aws-wrapper:postgresql://"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointAddress
                    - ":"
                    - Fn::ImportValue: !Sub ${StackPrefix}-RDSClusterEndpointPort
                    - "/"
                    - !Ref KeycloakDBName
          Secrets:
            - Name: KC_DB_USERNAME
              ValueFrom:
                Fn::Sub:
                  - "${SecretArn}:username::"
                  - SecretArn:
                      Fn::ImportValue: !Sub ${StackPrefix}-RDSSecretsManagerArn
            - Name: KC_DB_PASSWORD
              ValueFrom:
                Fn::Sub:
                  - "${SecretArn}:password::"
                  - SecretArn:
                      Fn::ImportValue: !Sub ${StackPrefix}-RDSSecretsManagerArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref KeycloakECSLogGroup
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: keycloak

# ECS Service for Keycloak
  KeycloakECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${StackPrefix}-KeycloakService
      Cluster: !Ref KeycloakECSCluster
      DesiredCount: !FindInMap [KeycloakServiceMap, !Ref EnvironmentType, DesiredCount]
      # TODO: adjust parameter
      HealthCheckGracePeriodSeconds: !FindInMap [KeycloakServiceMap, !Ref EnvironmentType, HealthCheckGracePeriodSeconds]
      TaskDefinition: !Ref KeycloakECSTaskDefinition
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, ContainerName]
          ContainerPort: !FindInMap [KeycloakTaskDefinitionMap, !Ref EnvironmentType, ContainerPort]
          TargetGroupArn: !Ref PublicALBForKeycloakDefaultTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetOneId
            - Fn::ImportValue: !Sub ${StackPrefix}-PrivateSubnetTwoId
          SecurityGroups:
            - Fn::ImportValue: !Sub ${StackPrefix}-PublicKeycloakECSSecurityGroup-ID
      # Rolling update
      DeploymentController:
        Type: ECS
      DeploymentConfiguration:
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
        MinimumHealthyPercent: !FindInMap [KeycloakServiceMap, !Ref EnvironmentType, RollingUpdateMinimumHealthyPercent]
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-KeycloakService
Outputs:
  PublicALBForKeycloakDNSName:
    Description: "Public ALB DNS Name for Keycloak"
    Value: !GetAtt PublicALBForKeycloak.DNSName
    Export: 
      Name: !Sub ${StackPrefix}-PubALBForKeycloak-DNS
  PublicALBForKeycloakUrl:
    Description: "Public ALB URL for Keycloak"
    Value: !Sub "http://${PublicALBForKeycloak.DNSName}"
    Export: 
      Name: !Sub ${StackPrefix}-PubALBForKeycloak-URL