AWSTemplateFormatVersion: 2010-09-09
Description: Secrets Manager Template(OIDC) for CloudFormation Demo. 
#Metadata: 

Parameters: 
  StackPrefix:
    Description: Stack Resource Name Prefix
    Type: String
    Default: Demo
  KeycloakRPSecretsName:
    Description: Secrets Manager Name for Keycloak Relying Party (RP)
    Type: String
    Default: /secrets/keycloak-secrets
  KeycloakRPClientId:
    NoEcho: 'true'
    Description: Relying Party (RP) Client ID for Keycloak OIDC
    Type: String
  KeycloakRPClientSecret:
    NoEcho: 'true'
    Description: Relying Party (RP) Client Secret for Keycloak OIDC
    Type: String
  KeycloakRSSecretsName:
    Description: Secrets Manager Name for Keycloak Resource Server (RS)
    Type: String
    Default: /secrets/keycloak-secrets
  KeycloakRSClientId:
    NoEcho: 'true'
    Description: Resource Server (RS) Client ID for Keycloak OIDC
    Type: String
  KeycloakRSClientSecret:
    NoEcho: 'true'
    Description: Resource Server (RS) Client Secret for Keycloak OIDC
    Type: String
  GitHubSecretsName:
    Description: Secrets Manager Name for GitHub
    Type: String
    Default: /secrets/github-secrets
  GitHubClientId:
    NoEcho: 'true'
    Description: Client ID for GitHub OIDC
    Type: String
  GitHubClientSecret:
    NoEcho: 'true'
    Description: Client Secret for GitHub OIDC
    Type: String
  GoogleSecretsName:
    Description: Secrets Manager Name for Google
    Type: String
    Default: /secrets/google-secrets
  GoogleClientId:
    NoEcho: 'true'
    Description: Client ID for Google OIDC
    Type: String
  GoogleClientSecret:
    NoEcho: 'true'
    Description: Client Secret for Google OIDC
    Type: String

#Mappings: 
#Conditions: 

Resources: 
# Secrets Manager
  # Keycloak Relying Party (RP) Secrets Manager
  KeycloakRPSecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref KeycloakRPSecretsName
      Description: Keycloak OIDC Secrets
      SecretString: !Sub '{"client-id": "${KeycloakRPClientId}", "client-secret": "${KeycloakRPClientSecret}"}'
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-Keycloak-SecretsManager
  KeycloakRSSecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref KeycloakRSSecretsName
      Description: Keycloak OIDC Secrets
      SecretString: !Sub '{"client-id": "${KeycloakRSClientId}", "client-secret": "${KeycloakRSClientSecret}"}'
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-KeycloakRS-SecretsManager
  GitHubSecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref GitHubSecretsName
      Description: GitHub OIDC Secrets
      SecretString: !Sub '{"client-id": "${GitHubClientId}", "client-secret": "${GitHubClientSecret}"}'
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-GitHub-SecretsManager
  GoogleSecretsManager:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref GoogleSecretsName
      Description: Google OIDC Secrets
      SecretString: !Sub '{"client-id": "${GoogleClientId}", "client-secret": "${GoogleClientSecret}"}'
      Tags:
        - Key: Name
          Value: !Sub ${StackPrefix}-Google-SecretsManager
Outputs:
  KeycloakRPSecretsManagerName:
    Description: Keycloak RP Secrets Manager Name
    Value: !Ref KeycloakRPSecretsName
    Export: 
      Name: !Sub ${StackPrefix}-KeycloakRPSecretsManagerName
  KeycloakRPSecretsManagerArn:
    Description: Keycloak RP Secrets Manager Arn
    Value: !Ref KeycloakRPSecretsManager
    Export: 
      Name: !Sub ${StackPrefix}-KeycloakRPSecretsManagerArn
  KeycloakRSSecretsManagerName:
    Description: Keycloak RS Secrets Manager Name
    Value: !Ref KeycloakRSSecretsName
    Export: 
      Name: !Sub ${StackPrefix}-KeycloakRSSecretsManagerName
  KeycloakRSSecretsManagerArn:
    Description: Keycloak RS Secrets Manager Arn
    Value: !Ref KeycloakRSSecretsManager
    Export: 
      Name: !Sub ${StackPrefix}-KeycloakRPSecretsManagerArn
  GitHubSecretsManagerName:
    Description: GitHub Secrets Manager Name
    Value: !Ref GitHubSecretsName
    Export: 
      Name: !Sub ${StackPrefix}-GitHubSecretsManagerName
  GitHubSecretsManagerArn:
    Description: GitHub Secrets Manager Arn
    Value: !Ref GitHubSecretsManager
    Export: 
      Name: !Sub ${StackPrefix}-GitHubSecretsManagerArn
  GoogleSecretsManagerName:
    Description: Google Secrets Manager Name
    Value: !Ref GoogleSecretsName
    Export: 
      Name: !Sub ${StackPrefix}-GoogleSecretsManagerName
  GoogleSecretsManagerArn:
    Description: Google Secrets Manager Arn
    Value: !Ref GoogleSecretsManager
    Export: 
      Name: !Sub ${StackPrefix}-GoogleSecretsManagerArn
